name: Tenkai-Web CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: make build
        uses: CultureHQ/actions-yarn@v1.0.1
        run: make build
