language: node_js

node_js:
  - '10'

branches:
 only:
   - develop
   - master
   - /^\d{2}\.\d\.\d+(-\d+)?$/

cache:
  npm: false

services:
  - docker

script:
  - make build
  - make lint
  - make container-image
  - make tag-image
  - make publish
